export const schoolsResponse200 = {
  data: {
    primary_schools: [
      {
        name: "École Paul-Bruchési (Paul-Bruchési)",
        address: "1310, boulevard St-Joseph Est",
        city: "Montréal",
        province: "QC",
        postalcode: "H2J1M2",
        country: "Canada",
        lat: 45.532152,
        lng: -73.581844,
        url: "http://www.paulbruchesi.qc.ca",
        proximity: {
          linear_distance: 306,
          walking: {
            quality: "calculated",
            distance: 463,
            travel_time: 5,
          },
        },
        school_attributes: {
          types: ["public"],
          levels: ["elementary"],
          languages: ["fr"],
        },
        school_board_attributes: {
          name: "Commission scolaire de Montréal",
          url: "www.csdm.qc.ca",
        },
      },
      {
        name: "École Paul-Bruchési (Service du dévelop. et de l'innov. professionnelle)",
        address: "4835, ave. Christophe-Colomb",
        city: "Montréal",
        province: "QC",
        postalcode: "H2J3G8",
        country: "Canada",
        lat: 45.530145,
        lng: -73.583171,
        url: "http://www.paulbruchesi.qc.ca",
        proximity: {
          linear_distance: 366,
          walking: {
            quality: "calculated",
            distance: 597,
            travel_time: 7,
          },
        },
        school_attributes: {
          types: ["public"],
          levels: ["elementary"],
          languages: ["fr"],
        },
        school_board_attributes: {
          name: "Commission scolaire de Montréal",
          url: "www.csdm.qc.ca",
        },
      },
      {
        name: "École Laurier",
        address: "505, avenue Laurier Est",
        city: "Montréal",
        province: "QC",
        postalcode: "H2J1E9",
        country: "Canada",
        lat: 45.528428,
        lng: -73.588676,
        url: "http://www.csdm.qc.ca/laurier",
        proximity: {
          linear_distance: 559,
          walking: {
            quality: "calculated",
            distance: 767,
            travel_time: 9,
          },
        },
        school_attributes: {
          types: ["public"],
          levels: ["elementary"],
          languages: ["fr"],
        },
        school_board_attributes: {
          name: "Commission scolaire de Montréal",
          url: "www.csdm.qc.ca",
        },
      },
      {
        name: "École Saint-Pierre-Claver",
        address: "2110, boulevard St-Joseph Est",
        city: "Montréal",
        province: "QC",
        postalcode: "H2H1E7",
        country: "Canada",
        lat: 45.537465,
        lng: -73.576424,
        url: "http://www.csdm.qc.ca/saint-pierre-claver/",
        proximity: {
          linear_distance: 872,
        },
        school_attributes: {
          types: ["public"],
          levels: ["elementary"],
          languages: ["fr"],
        },
        school_board_attributes: {
          name: "Commission scolaire de Montréal",
          url: "www.csdm.qc.ca",
        },
      },
      {
        name: "École Saint-Étienne",
        address: "5959, avenue Christophe-Colomb",
        city: "Montréal",
        province: "QC",
        postalcode: "H2S2G3",
        country: "Canada",
        lat: 45.536091,
        lng: -73.596473,
        url: "http://www.csdm.qc.ca/st_etienne/",
        proximity: {
          linear_distance: 915,
          walking: {
            quality: "calculated",
            distance: 1024,
            travel_time: 12,
          },
        },
        school_attributes: {
          types: ["public"],
          levels: ["elementary"],
          languages: ["fr"],
        },
        school_board_attributes: {
          name: "Commission scolaire de Montréal",
          url: "www.csdm.qc.ca",
        },
      },
      {
        name: "École Le Vitrail",
        address: "5927, rue Boyer",
        city: "Montréal",
        province: "QC",
        postalcode: "H2S2H8",
        country: "Canada",
        lat: 45.535093,
        lng: -73.59726,
        url: "http://www.csdm.qc.ca/le-vitrail/",
        proximity: {
          linear_distance: 938,
          walking: {
            quality: "calculated",
            distance: 1115,
            travel_time: 13,
          },
        },
        school_attributes: {
          types: ["public"],
          levels: ["elementary", "secondary"],
          languages: ["fr"],
        },
        school_board_attributes: {
          name: "Commission scolaire de Montréal",
          url: "www.csdm.qc.ca",
        },
      },
      {
        name: "École Lanaudière",
        address: "4300, rue de Lanaudière",
        city: "Montréal",
        province: "QC",
        postalcode: "H2J3N9",
        country: "Canada",
        lat: 45.528738,
        lng: -73.574506,
        url: "http://www.csdm.qc.ca/Lanaudiere/",
        proximity: {
          linear_distance: 983,
        },
        school_attributes: {
          types: ["public"],
          levels: ["elementary"],
          languages: ["fr"],
        },
        school_board_attributes: {
          name: "Commission scolaire de Montréal",
          url: "www.csdm.qc.ca",
        },
      },
      {
        name: "École Madeleine-de-Verchères",
        address: "6017, rue Cartier",
        city: "Montréal",
        province: "QC",
        postalcode: "H2G2V4",
        country: "Canada",
        lat: 45.542123,
        lng: -73.592016,
        url: "http://www.csdm.qc.ca/mdv",
        proximity: {
          linear_distance: 1133,
        },
        school_attributes: {
          types: ["public"],
          levels: ["elementary"],
          languages: ["fr"],
        },
        school_board_attributes: {
          name: "Commission scolaire de Montréal",
          url: "www.csdm.qc.ca",
        },
      },
      {
        name: "École Saint-Enfant-Jésus",
        address: "75, rue Villeneuve Est",
        city: "Montréal",
        province: "QC",
        postalcode: "H2T1L1",
        country: "Canada",
        lat: 45.522546,
        lng: -73.589408,
        url: "http://www.csdm.qc.ca/st-enfant-jesus/",
        proximity: {
          linear_distance: 1196,
        },
        school_attributes: {
          types: ["public"],
          levels: ["elementary"],
          languages: ["fr"],
        },
        school_board_attributes: {
          name: "Commission scolaire de Montréal",
          url: "www.csdm.qc.ca",
        },
      },
      {
        name: "École Louis-Hippolyte-Lafontaine",
        address: "4245, rue Berri",
        city: "Montréal",
        province: "QC",
        postalcode: "H2J2P9",
        country: "Canada",
        lat: 45.523364,
        lng: -73.577914,
        url: "http://www.csdm.qc.ca/lh-lafontaine/",
        proximity: {
          linear_distance: 1224,
        },
        school_attributes: {
          types: ["public"],
          levels: ["elementary"],
          languages: ["fr"],
        },
        school_board_attributes: {
          name: "Commission scolaire de Montréal",
          url: "www.csdm.qc.ca",
        },
      },
    ],
    high_schools: [
      {
        name: "École Le Vitrail",
        address: "5927, rue Boyer",
        city: "Montréal",
        province: "QC",
        postalcode: "H2S2H8",
        country: "Canada",
        lat: 45.535093,
        lng: -73.59726,
        url: "http://www.csdm.qc.ca/le-vitrail/",
        proximity: {
          linear_distance: 938,
          walking: {
            quality: "calculated",
            distance: 1115,
            travel_time: 13,
          },
        },
        school_attributes: {
          types: ["public"],
          levels: ["elementary", "secondary"],
          languages: ["fr"],
        },
        school_board_attributes: {
          name: "Commission scolaire de Montréal",
          url: "www.csdm.qc.ca",
        },
      },
      {
        name: "Collège Français, Campus Montaigne",
        address: "172, avenue Fairmount Ouest",
        city: "Montréal",
        province: "QC",
        postalcode: "H2T1E2",
        country: "Canada",
        lat: 45.525422,
        lng: -73.593132,
        proximity: {
          linear_distance: 1024,
          walking: {
            quality: "calculated",
            distance: 1366,
            travel_time: 17,
          },
        },
        school_attributes: {
          types: ["private"],
          levels: ["secondary"],
        },
        school_board_attributes: {},
      },
      {
        name: "École Robert-Gravel",
        address: "38, avenue Fairmount Est",
        city: "Montréal",
        province: "QC",
        postalcode: "H2T1C9",
        country: "Canada",
        lat: 45.524638,
        lng: -73.593701,
        url: "http://www.csdm.qc.ca/st-louis",
        proximity: {
          linear_distance: 1120,
          walking: {
            quality: "calculated",
            distance: 1463,
            travel_time: 18,
          },
        },
        school_attributes: {
          types: ["public"],
          levels: ["secondary"],
          languages: ["fr"],
        },
        school_board_attributes: {
          name: "Commission scolaire de Montréal",
          url: "www.csdm.qc.ca",
        },
      },
      {
        name: "École Père-Marquette",
        address: "6030, rue Marquette",
        city: "Montréal",
        province: "QC",
        postalcode: "H2G2Y2",
        country: "Canada",
        lat: 45.541161,
        lng: -73.59408,
        url: "http://www.csdm.qc.ca/P_Marquette_S/",
        proximity: {
          linear_distance: 1125,
          walking: {
            quality: "calculated",
            distance: 1503,
            travel_time: 18,
          },
        },
        school_attributes: {
          types: ["public"],
          levels: ["secondary"],
          languages: ["fr"],
        },
        school_board_attributes: {
          name: "Commission scolaire de Montréal",
          url: "www.csdm.qc.ca",
        },
      },
      {
        name: "École Lucien-Guilbault inc.- secteur 2e cycle du secondaire",
        address: "6235, rue Saint-Hubert, 2e étage",
        city: "Montréal",
        province: "QC",
        postalcode: "H2S2L9",
        country: "Canada",
        lat: 45.535119,
        lng: -73.600364,
        url: "http://www.lucien-guilbault.ca",
        proximity: {
          linear_distance: 1174,
          walking: {
            quality: "calculated",
            distance: 1433,
            travel_time: 17,
          },
        },
        school_attributes: {
          types: ["private"],
          levels: ["secondary"],
        },
        school_board_attributes: {},
      },
      {
        name: "École Jeanne-Mance",
        address: "4240, rue de Bordeaux",
        city: "Montréal",
        province: "QC",
        postalcode: "H2H1Z5",
        country: "Canada",
        lat: 45.532295,
        lng: -73.569906,
        url: "http://www.csdm.qc.ca/jeanne-mance",
        proximity: {
          linear_distance: 1224,
        },
        school_attributes: {
          types: ["public"],
          levels: ["secondary"],
          languages: ["fr"],
        },
        school_board_attributes: {
          name: "Commission scolaire de Montréal",
          url: "www.csdm.qc.ca",
        },
      },
      {
        name: "École Irénée-Lussier (Jeanne-Mance)",
        address: "4240, rue de Bordeaux",
        city: "Montréal",
        province: "QC",
        postalcode: "H2H1Z5",
        country: "Canada",
        lat: 45.532295,
        lng: -73.569906,
        proximity: {
          linear_distance: 1224,
        },
        school_attributes: {
          types: ["public"],
          levels: ["secondary"],
          languages: ["fr"],
        },
        school_board_attributes: {
          name: "Commission scolaire de Montréal",
          url: "www.csdm.qc.ca",
        },
      },
      {
        name: "École secondaire M.I.N.D.",
        address: "4563, rue Saint-Urbain",
        city: "Montréal",
        province: "QC",
        postalcode: "H2T2V9",
        country: "Canada",
        lat: 45.519649,
        lng: -73.588433,
        url: "http://www.emsb.qc.ca/Mind/",
        proximity: {
          linear_distance: 1497,
        },
        school_attributes: {
          types: ["public"],
          levels: ["secondary"],
          languages: ["en"],
        },
        school_board_attributes: {
          name: "Commission scolaire English-Montréal",
          url: "www.emsb.qc.ca",
        },
      },
      {
        name: "Collège Français, Campus de Montréal",
        address: "185, avenue Fairmount Ouest",
        city: "Montréal",
        province: "QC",
        postalcode: "H2T2M6",
        country: "Canada",
        lat: 45.521624,
        lng: -73.596811,
        url: "http://www.collegefrancais.ca",
        proximity: {
          linear_distance: 1534,
        },
        school_attributes: {
          types: ["private"],
          levels: ["secondary"],
        },
        school_board_attributes: {},
      },
      {
        name: "École communautaire Belz, Campus Jeanne-Mance, section anglaise",
        address: "5030, rue Jeanne-Mance",
        city: "Montréal",
        province: "QC",
        postalcode: "H2V4J8",
        country: "Canada",
        lat: 45.519797,
        lng: -73.594704,
        proximity: {
          linear_distance: 1627,
        },
        school_attributes: {
          types: ["private"],
          levels: ["secondary"],
        },
        school_board_attributes: {},
      },
    ],
  },
  meta: {
    message: "Successfully called v3/schools API.",
    type: "LocalLogic.API.Success",
    statusCode: 200,
    counts: {
      primary_schools: 10,
      high_schools: 10,
    },
  },
};
