module.exports = {
  semi: true,
  tabWidth: 2,
  useTabs: false,
  printWidth: 100,
  endOfLine: "lf",
  singleQuote: false,
  insertPragma: false,
  requirePragma: false,
  trailingComma: "es5",
  arrowParens: "always",
  bracketSpacing: true,
  proseWrap: "preserve",
  quoteProps: "as-needed",
  htmlWhitespaceSensitivity: "css",
  importOrder: ["^@local-logic/(.*)$", "<THIRD_PARTY_MODULES>", "^[./]"],
};
