export const poisResponse200 = {
  data: {
    groceries: [
      {
        name: "Metro",
        address: "1293 Av Laurier E",
        city: "Montréal",
        province: "QC",
        postalcode: "H2J1H2",
        country: "Canada",
        lat: 45.53287,
        lng: -73.58456,
        url: "http://metro.ca",
        proximity: {
          linear_distance: 81,
          walking: {
            quality: "calculated",
            distance: 236,
            travel_time: 2,
          },
        },
      },
      {
        name: "Metro",
        address: "5300 Rue Saint-Hubert",
        city: "Montréal",
        province: "QC",
        postalcode: "H2J2Y5",
        country: "Canada",
        lat: 45.53004,
        lng: -73.590744,
        url: "http://metro.ca",
        proximity: {
          linear_distance: 516,
          walking: {
            quality: "calculated",
            distance: 765,
            travel_time: 9,
          },
        },
      },
      {
        name: "Intermarch Boyer",
        address: "1000 Avenue du Mont-Royal E",
        city: "Montréal",
        province: "QC",
        postalcode: "H2J1X6",
        country: "Canada",
        lat: 45.52748,
        lng: -73.5795,
        url: "http://intermarcheboyer.com",
        proximity: {
          linear_distance: 773,
          walking: {
            quality: "calculated",
            distance: 1044,
            travel_time: 13,
          },
        },
      },
      {
        name: "Intermarche du Plateau",
        address: "1670 Avenue du Mont-Royal E",
        city: "Montréal",
        province: "QC",
        postalcode: "H2J1Z5",
        country: "Canada",
        lat: 45.532345,
        lng: -73.574915,
        proximity: {
          linear_distance: 835,
          walking: {
            quality: "calculated",
            distance: 1233,
            travel_time: 15,
          },
        },
      },
      {
        name: "Épicerie de Grand-Pre",
        address: "4800 De Grand-Pre Rue",
        city: "Montréal",
        province: "QC",
        postalcode: "H2T2H8",
        country: "Canada",
        lat: 45.524808,
        lng: -73.586239,
        proximity: {
          linear_distance: 908,
          walking: {
            quality: "calculated",
            distance: 1232,
            travel_time: 15,
          },
        },
      },
      {
        name: "Marché Primavera",
        address: "5200 Saint-Laurent Boul",
        city: "Montréal",
        province: "QC",
        postalcode: "H2T1S1",
        country: "Canada",
        lat: 45.52374,
        lng: -73.59486,
        proximity: {
          linear_distance: 1254,
        },
      },
      {
        name: "Metro",
        address: "2275 Av Du Mont-Royal E",
        city: "Montréal",
        province: "QC",
        postalcode: "H2H1K7",
        country: "Canada",
        lat: 45.537269,
        lng: -73.570502,
        url: "http://metro.ca",
        proximity: {
          linear_distance: 1269,
        },
      },
      {
        name: "Pousse l'Ananas",
        address: "6346 Saint-Hubert Rue",
        city: "Montréal",
        province: "QC",
        postalcode: "H2S2M2",
        country: "Canada",
        lat: 45.535465,
        lng: -73.60198,
        proximity: {
          linear_distance: 1305,
        },
      },
      {
        name: "Les Marchés Tradition",
        address: "1200 Rue Beaubien E",
        city: "Montréal",
        province: "QC",
        postalcode: "H2S1T7",
        country: "Canada",
        lat: 45.53865,
        lng: -73.600525,
        url: "https://www.marchestradition.com/magasin/8721",
        proximity: {
          linear_distance: 1322,
        },
      },
      {
        name: "IGA Épicerie F Chartrand",
        address: "2340 Rosemont Boul",
        city: "Montréal",
        province: "QC",
        postalcode: "H2G1T7",
        country: "Canada",
        lat: 45.54483,
        lng: -73.58741,
        url: "https://www.iga.net/fr/recherche_de_magasin/magasin/0151?utm_source=I&utm_medium=lpm&utm_campaign=SobeysMontreal",
        proximity: {
          linear_distance: 1326,
        },
      },
      {
        name: "Universal Meat Market",
        address: "89 Avenue du Mont-Royal E",
        city: "Montréal",
        province: "QC",
        postalcode: "H2T1N6",
        country: "Canada",
        lat: 45.521035,
        lng: -73.585705,
        url: "http://universalmeat.foodpages.ca",
        proximity: {
          linear_distance: 1327,
        },
      },
      {
        name: "Rachelle-Bery Epiceries Santé",
        address: "4201 Saint-Denis Rue",
        city: "Montréal",
        province: "QC",
        postalcode: "H2J2K9",
        country: "Canada",
        lat: 45.52205,
        lng: -73.578255,
        url: "https://www.rachellebery.ca/magasin/?utm_source=I&utm_medium=lpm&utm_campaign=SobeysMontreal",
        proximity: {
          linear_distance: 1342,
        },
      },
      {
        name: "Maxi",
        address: "2535 Rue Masson",
        city: "Montréal",
        province: "QC",
        postalcode: "H1Y1V7",
        country: "Canada",
        lat: 45.54384,
        lng: -73.577774,
        url: "https://www.maxi.ca/store-locator/details/8632",
        proximity: {
          linear_distance: 1353,
        },
      },
      {
        name: "Casa Latina",
        address: "4561 Saint-Laurent Boul",
        city: "Montréal",
        province: "QC",
        postalcode: "H2T1R2",
        country: "Canada",
        lat: 45.52079,
        lng: -73.58748,
        url: "https://casa-latina.org",
        proximity: {
          linear_distance: 1362,
        },
      },
      {
        name: "Sobeys",
        address: "2544 Masson Rue",
        city: "Montréal",
        province: "QC",
        postalcode: "H1Y1V8",
        country: "Canada",
        lat: 45.54383,
        lng: -73.57709,
        url: "http://shell.ca",
        proximity: {
          linear_distance: 1377,
        },
      },
      {
        name: "Épicerie Kun Teng",
        address: "4216 De Lorimier Av",
        city: "Montréal",
        province: "QC",
        postalcode: "H2H2B1",
        country: "Canada",
        lat: 45.532852,
        lng: -73.567744,
        proximity: {
          linear_distance: 1390,
        },
      },
      {
        name: "Italo Super Market",
        address: "6433 Papineau Av",
        city: "Montréal",
        province: "QC",
        postalcode: "H2G2X1",
        country: "Canada",
        lat: 45.54316,
        lng: -73.5962,
        proximity: {
          linear_distance: 1401,
        },
      },
      {
        name: "Épicerie & Boucherie Sa & Fils",
        address: "4701 Rue Saint-Urbain",
        city: "Montréal",
        province: "QC",
        postalcode: "H2T2V9",
        country: "Canada",
        lat: 45.52038,
        lng: -73.59017,
        proximity: {
          linear_distance: 1444,
        },
      },
      {
        name: "Supermarché Rahman",
        address: "151 Avenue Laurier O",
        city: "Montréal",
        province: "QC",
        postalcode: "H2T2N6",
        country: "Canada",
        lat: 45.521295,
        lng: -73.594535,
        proximity: {
          linear_distance: 1473,
        },
      },
      {
        name: "Provigo",
        address: "50 Du Mont-Royal Av O",
        city: "Montréal",
        province: "QC",
        postalcode: "H2T2S3",
        country: "Canada",
        lat: 45.519453,
        lng: -73.586848,
        url: "https://www.provigo.ca/store-locator/details/8613",
        proximity: {
          linear_distance: 1506,
        },
      },
      {
        name: "Sabor Latino",
        address: "4387 Boulevard St-Laurent",
        city: "Montréal",
        province: "QC",
        postalcode: "H2W1Z8",
        country: "Canada",
        lat: 45.519395,
        lng: -73.58456,
        proximity: {
          linear_distance: 1511,
        },
      },
      {
        name: "Metro",
        address: "2008 Rue Gauthier",
        city: "Montréal",
        province: "QC",
        postalcode: "H2K1A7",
        country: "Canada",
        lat: 45.531265,
        lng: -73.56553,
        url: "http://metro.ca",
        proximity: {
          linear_distance: 1574,
        },
      },
      {
        name: "Shusi 111",
        address: "111 Avenue du Mont-Royal O",
        city: "Montréal",
        province: "QC",
        postalcode: "H2T2S9",
        country: "Canada",
        lat: 45.51881,
        lng: -73.58772,
        proximity: {
          linear_distance: 1583,
        },
      },
      {
        name: "IGA Marché Barcelo",
        address: "900 Saint-Zotique Rue E",
        city: "Montréal",
        province: "QC",
        postalcode: "H2S1M8",
        country: "Canada",
        lat: 45.538296,
        lng: -73.6056,
        url: "https://www.iga.net/fr/recherche_de_magasin/magasin/0454?utm_source=I&utm_medium=lpm&utm_campaign=SobeysMontreal",
        proximity: {
          linear_distance: 1666,
        },
      },
      {
        name: "IGA Famille Barcelo Saint-Zotique",
        address: "900 Saint-Zotique Rue E",
        city: "Montréal",
        province: "QC",
        postalcode: "H2S1M8",
        country: "Canada",
        lat: 45.538296,
        lng: -73.6056,
        url: "https://www.iga.net/fr/recherche_de_magasin/magasin/0454",
        proximity: {
          linear_distance: 1666,
        },
      },
      {
        name: "P à Nature",
        address: "5029 Avenue du Parc",
        city: "Montréal",
        province: "QC",
        postalcode: "H2V4E9",
        country: "Canada",
        lat: 45.519385,
        lng: -73.594985,
        url: "http://pa-nature.supermarchepa.com",
        proximity: {
          linear_distance: 1678,
        },
      },
      {
        name: "Chouricor",
        address: "4031 De Bullion Rue",
        city: "Montréal",
        province: "QC",
        postalcode: "H2W2E3",
        country: "Canada",
        lat: 45.51835,
        lng: -73.57787,
        proximity: {
          linear_distance: 1733,
        },
      },
      {
        name: "John Choynowski Grocery",
        address: "4031 De Bullion Rue",
        city: "Montréal",
        province: "QC",
        postalcode: "H2W2E3",
        country: "Canada",
        lat: 45.51835,
        lng: -73.57787,
        proximity: {
          linear_distance: 1733,
        },
      },
      {
        name: "Les Marchés Tradition",
        address: "3795 Rue Saint-Andre",
        city: "Montréal",
        province: "QC",
        postalcode: "H2L3V6",
        country: "Canada",
        lat: 45.521694,
        lng: -73.56984,
        url: "https://www.marchestradition.com/magasin/8681",
        proximity: {
          linear_distance: 1754,
        },
      },
      {
        name: "Segal's Market",
        address: "4001 Boulevard St-Laurent",
        city: "Montréal",
        province: "QC",
        postalcode: "H2W1Y4",
        country: "Canada",
        lat: 45.51689,
        lng: -73.57885,
        proximity: {
          linear_distance: 1863,
        },
      },
      {
        name: "Bentzys Food Depot",
        address: "5540 Rue Hutchison",
        city: "Outremont",
        province: "QC",
        postalcode: "H2V4B3",
        country: "Canada",
        lat: 45.521282,
        lng: -73.602844,
        proximity: {
          linear_distance: 1869,
        },
      },
      {
        name: "Épicerie Colonial",
        address: "3916 Coloniale Av",
        city: "Montréal",
        province: "QC",
        postalcode: "H2W2B6",
        country: "Canada",
        lat: 45.51709,
        lng: -73.57711,
        proximity: {
          linear_distance: 1885,
        },
      },
      {
        name: "GJMRK Operations",
        address: "51 Duluth Av O",
        city: "Montréal",
        province: "QC",
        postalcode: "H2W1J6",
        country: "Canada",
        lat: 45.516407,
        lng: -73.580086,
        proximity: {
          linear_distance: 1891,
        },
      },
      {
        name: "Metro",
        address: "1550 Rue Belanger",
        city: "Montréal",
        province: "QC",
        postalcode: "H2G1A8",
        country: "Canada",
        lat: 45.5453,
        lng: -73.60425,
        url: "http://metro.ca",
        proximity: {
          linear_distance: 1997,
        },
      },
      {
        name: "Librairie Espagnole L Espanola",
        address: "3811 Saint-Laurent Boul",
        city: "Montréal",
        province: "QC",
        postalcode: "H2W1X9",
        country: "Canada",
        lat: 45.51565,
        lng: -73.57603,
        url: "https://lespanola.com",
        proximity: {
          linear_distance: 2065,
        },
      },
      {
        name: "Projets Parts-Part du Chef",
        address: "4100 Andre-Laurendeau Rue",
        city: "Montréal",
        province: "QC",
        postalcode: "H1Y3N6",
        country: "Canada",
        lat: 45.542989,
        lng: -73.562779,
        url: "https://www.groupepart.ca",
        proximity: {
          linear_distance: 2097,
        },
      },
      {
        name: "Les Marchés Tradition",
        address: "3695 Boul Saint-Laurent",
        city: "Montréal",
        province: "QC",
        postalcode: "H2X2V7",
        country: "Canada",
        lat: 45.514851,
        lng: -73.574509,
        url: "https://www.marchestradition.com/magasin/8785/",
        proximity: {
          linear_distance: 2192,
        },
      },
      {
        name: "Alimentation Poivre & Sel",
        address: "3245 Masson Rue",
        city: "Montréal",
        province: "QC",
        postalcode: "H1Y1Y4",
        country: "Canada",
        lat: 45.550793,
        lng: -73.57343,
        proximity: {
          linear_distance: 2196,
        },
      },
      {
        name: "Marché Sept Jours",
        address: "2601 Saint-Zotique Rue E",
        city: "Montréal",
        province: "QC",
        postalcode: "H1Y1E1",
        country: "Canada",
        lat: 45.55216,
        lng: -73.59395,
        proximity: {
          linear_distance: 2230,
        },
      },
      {
        name: "Provigo",
        address: "2925 Rue Rachel E",
        city: "Montréal",
        province: "QC",
        postalcode: "H1W3Z8",
        country: "Canada",
        lat: 45.544345,
        lng: -73.561845,
        url: "https://www.provigo.ca/store-locator/?storeId=8449",
        proximity: {
          linear_distance: 2241,
        },
      },
      {
        name: "Maxi",
        address: "2925 Rue Sherbrooke E",
        city: "Montréal",
        province: "QC",
        postalcode: "H1W1B2",
        country: "Canada",
        lat: 45.54082,
        lng: -73.55895,
        url: "https://www.maxi.ca/store-locator/details/8797",
        proximity: {
          linear_distance: 2251,
        },
      },
      {
        name: "Marché Select-Choix",
        address: "3275 Rue Masson",
        city: "Montréal",
        province: "QC",
        postalcode: "H1X1R3",
        country: "Canada",
        lat: 45.55133,
        lng: -73.57315,
        url: "https://marcheami.ca",
        proximity: {
          linear_distance: 2260,
        },
      },
      {
        name: "Marché Nascimento & Brito",
        address: "67 Rue Prince-Arthur E",
        city: "Montréal",
        province: "QC",
        postalcode: "H2X1B4",
        country: "Canada",
        lat: 45.514585,
        lng: -73.572145,
        proximity: {
          linear_distance: 2297,
        },
      },
      {
        name: "Provigo",
        address: "3185 Beaubien Rue E",
        city: "Montréal",
        province: "QC",
        postalcode: "H1Y1H5",
        country: "Canada",
        lat: 45.55418,
        lng: -73.58743,
        url: "https://www.provigo.ca/store-locator/details/8198",
        proximity: {
          linear_distance: 2362,
        },
      },
      {
        name: "Supermarché Brito",
        address: "67 Prince-Arthur Rue E",
        city: "Montréal",
        province: "QC",
        postalcode: "H2X1S5",
        country: "Canada",
        lat: 45.513178,
        lng: -73.573241,
        proximity: {
          linear_distance: 2402,
        },
      },
      {
        name: "Marché Patry",
        address: "1685 Amherst Rue",
        city: "Montréal",
        province: "QC",
        postalcode: "H2L3L4",
        country: "Canada",
        lat: 45.518941,
        lng: -73.560051,
        proximity: {
          linear_distance: 2528,
        },
      },
      {
        name: "Marché de Rouen Plus",
        address: "2850 De Rouen Rue",
        city: "Montréal",
        province: "QC",
        postalcode: "H2K1N7",
        country: "Canada",
        lat: 45.537754,
        lng: -73.553314,
        proximity: {
          linear_distance: 2570,
        },
      },
      {
        name: "IGA Hochelaga",
        address: "2600 Rue Ontario E",
        city: "Montréal",
        province: "QC",
        postalcode: "H2K4K4",
        country: "Canada",
        lat: 45.53359,
        lng: -73.552065,
        url: "https://www.iga.net/fr/recherche_de_magasin/magasin/8038",
        proximity: {
          linear_distance: 2613,
        },
      },
      {
        name: "Épicerie Hiep Phat",
        address: "2679 Rue Ontario E",
        city: "Montréal",
        province: "QC",
        postalcode: "H2K1X1",
        country: "Canada",
        lat: 45.53445,
        lng: -73.55169,
        proximity: {
          linear_distance: 2646,
        },
      },
      {
        name: "Metro Plus",
        address: "3600 Boulevard St-Joseph E",
        city: "Montréal",
        province: "QC",
        postalcode: "H1X1W6",
        country: "Canada",
        lat: 45.5523669,
        lng: -73.5658754,
        url: "http://metro.ca",
        proximity: {
          linear_distance: 2647,
        },
      },
      {
        name: "Metro",
        address: "Suite 5100, 3575 Avenue du Parc",
        city: "Montréal",
        province: "QC",
        postalcode: "H2X3P9",
        country: "Canada",
        lat: 45.510225,
        lng: -73.57511,
        url: "http://metro.ca",
        proximity: {
          linear_distance: 2657,
        },
      },
      {
        name: "Les Marchés Tradition",
        address: "2535 Rue Jean-Talon E",
        city: "Montréal",
        province: "QC",
        postalcode: "H2A1T6",
        country: "Canada",
        lat: 45.554226,
        lng: -73.601875,
        url: "https://www.marchestradition.com/magasin/749",
        proximity: {
          linear_distance: 2681,
        },
      },
      {
        name: "Marché Lobo",
        address: "3509 Avenue du Parc",
        city: "Montréal",
        province: "QC",
        postalcode: "H2X2H8",
        country: "Canada",
        lat: 45.509675,
        lng: -73.573765,
        proximity: {
          linear_distance: 2749,
        },
      },
      {
        name: "New Madina Super Market",
        address: "17 Rue Ontario E",
        city: "Montréal",
        province: "QC",
        postalcode: "H2X1G8",
        country: "Canada",
        lat: 45.511757,
        lng: -73.56686,
        url: "http://new-madina-super-market-inc.foodpages.ca",
        proximity: {
          linear_distance: 2774,
        },
      },
      {
        name: "Marché Steve-Anna",
        address: "3302 Belanger Rue",
        city: "Montréal",
        province: "QC",
        postalcode: "H1X1A1",
        country: "Canada",
        lat: 45.557884,
        lng: -73.59316,
        proximity: {
          linear_distance: 2832,
        },
      },
      {
        name: "Metro Plus",
        address: "1955 Rue Sainte-Catherine E",
        city: "Montréal",
        province: "QC",
        postalcode: "H2K2H6",
        country: "Canada",
        lat: 45.523937,
        lng: -73.551384,
        url: "http://metro.ca",
        proximity: {
          linear_distance: 2848,
        },
      },
      {
        name: "Super Green",
        address: "434 Milton Rue",
        city: "Montréal",
        province: "QC",
        postalcode: "H2X1W1",
        country: "Canada",
        lat: 45.508286,
        lng: -73.57451,
        proximity: {
          linear_distance: 2877,
        },
      },
      {
        name: "Provigo",
        address: "3421 Avenue du Parc",
        city: "Montréal",
        province: "QC",
        postalcode: "H2X2H6",
        country: "Canada",
        lat: 45.50877,
        lng: -73.571665,
        url: "https://www.provigo.ca/store-locator/details/8656",
        proximity: {
          linear_distance: 2901,
        },
      },
      {
        name: "IGA Express",
        address: "1446 Ave Boul",
        city: "Montréal",
        province: "QC",
        postalcode: "H2X1J5",
        country: "Canada",
        lat: 45.510652,
        lng: -73.565162,
        url: "https://www.iga.net/en/find_a_store/store/5924-sobeys-capital-inc--ll-q--ll-spectacles",
        proximity: {
          linear_distance: 2948,
        },
      },
      {
        name: "Marché Dussault",
        address: "3451 Rue Hochelaga",
        city: "Montréal",
        province: "QC",
        postalcode: "H1W1H6",
        country: "Canada",
        lat: 45.54571,
        lng: -73.552345,
        proximity: {
          linear_distance: 2952,
        },
      },
      {
        name: "Marché Assaka",
        address: "3270 Jean-Talon Rue E",
        city: "Montréal",
        province: "QC",
        postalcode: "H2A1W3",
        country: "Canada",
        lat: 45.559223,
        lng: -73.597694,
        proximity: {
          linear_distance: 3067,
        },
      },
      {
        name: "Marché Adco",
        address: "3279 Rue Jean-Talon E",
        city: "Montréal",
        province: "QC",
        postalcode: "H2A1W4",
        country: "Canada",
        lat: 45.55942,
        lng: -73.597995,
        proximity: {
          linear_distance: 3095,
        },
      },
      {
        name: "Marché Axep Mont Royal",
        address: "3920 Du Mont-Royal Av E",
        city: "Montréal",
        province: "QC",
        postalcode: "H1X1Y1",
        country: "Canada",
        lat: 45.554312,
        lng: -73.559887,
        url: "http://www.axep.com",
        proximity: {
          linear_distance: 3105,
        },
      },
      {
        name: "Marchés Louise Menard",
        address: "150 Rue Ste-Catherine O",
        city: "Montréal",
        province: "QC",
        postalcode: "H2X3Y2",
        country: "Canada",
        lat: 45.50768,
        lng: -73.56496,
        proximity: {
          linear_distance: 3239,
        },
      },
      {
        name: "Rachelle-Bery Boutiques Santé",
        address: "150 Rue Ste-Catherine O",
        city: "Montréal",
        province: "QC",
        postalcode: "H2X3Y2",
        country: "Canada",
        lat: 45.50768,
        lng: -73.56496,
        url: "https://www.rachellebery.ca/magasin/8345",
        proximity: {
          linear_distance: 3239,
        },
      },
      {
        name: "IGA Marché Louise Menard",
        address: "5 Complexe Desjardins",
        city: "Montréal",
        province: "QC",
        postalcode: "H5B1B5",
        country: "Canada",
        lat: 45.5072384,
        lng: -73.56596145,
        url: "http://iga.ca",
        proximity: {
          linear_distance: 3244,
        },
      },
      {
        name: "La Compagnie Shung Lee",
        address: "1106 Saint-Laurent Boul",
        city: "Montréal",
        province: "QC",
        postalcode: "H2Z1J5",
        country: "Canada",
        lat: 45.508415,
        lng: -73.56137,
        proximity: {
          linear_distance: 3319,
        },
      },
      {
        name: "Épicerie Heng Heng Chanchaya",
        address: "1071 Boulevard St-Laurent",
        city: "Montréal",
        province: "QC",
        postalcode: "H2Z1J6",
        country: "Canada",
        lat: 45.5086,
        lng: -73.560695,
        proximity: {
          linear_distance: 3332,
        },
      },
      {
        name: "Kien Xuong",
        address: "1076 Boulevard St-Laurent",
        city: "Montréal",
        province: "QC",
        postalcode: "H2Z1J5",
        country: "Canada",
        lat: 45.50828,
        lng: -73.56067,
        proximity: {
          linear_distance: 3362,
        },
      },
      {
        name: "Sang Yuen Co",
        address: "1111 Saint-Urbain Rue",
        city: "Montréal",
        province: "QC",
        postalcode: "H2Z1Y6",
        country: "Canada",
        lat: 45.50763,
        lng: -73.561844,
        proximity: {
          linear_distance: 3371,
        },
      },
      {
        name: "Marché le Quartier",
        address: "1546 Dezery Rue",
        city: "Montréal",
        province: "QC",
        postalcode: "H1W2R4",
        country: "Canada",
        lat: 45.53968,
        lng: -73.54336,
        proximity: {
          linear_distance: 3373,
        },
      },
      {
        name: "Kien Vinh Trading",
        address: "1062 Saint-Laurent Boul",
        city: "Montréal",
        province: "QC",
        postalcode: "H2Z1J5",
        country: "Canada",
        lat: 45.508076,
        lng: -73.56044,
        proximity: {
          linear_distance: 3391,
        },
      },
      {
        name: "Cafa Humble Lion",
        address: "904 Rue Sherbrooke O",
        city: "Montréal",
        province: "QC",
        postalcode: "H3A1G3",
        country: "Canada",
        lat: 45.50334,
        lng: -73.57498,
        url: "http://cafehumblelion.com",
        proximity: {
          linear_distance: 3397,
        },
      },
      {
        name: "Uni",
        address: "1029 Boulevard St-Laurent",
        city: "Montréal",
        province: "QC",
        postalcode: "H2Z1J4",
        country: "Canada",
        lat: 45.508135,
        lng: -73.559855,
        url: "https://www.umontreal.ca",
        proximity: {
          linear_distance: 3413,
        },
      },
      {
        name: "Olly Fresco's",
        address: "625 Rue Ste-Catherine O",
        city: "Montréal",
        province: "QC",
        postalcode: "H3B1B7",
        country: "Canada",
        lat: 45.50368,
        lng: -73.569945,
        url: "http://www.ollyfrescos.ca",
        proximity: {
          linear_distance: 3477,
        },
      },
      {
        name: "Supermarché G & D",
        address: "1006 Saint-Laurent Boul",
        city: "Montréal",
        province: "QC",
        postalcode: "H2Z1J3",
        country: "Canada",
        lat: 45.50759,
        lng: -73.559525,
        url: "https://gdsupermarche.com",
        proximity: {
          linear_distance: 3477,
        },
      },
      {
        name: "Le Point de Rosee",
        address: "4288 Beaubien Rue E",
        city: "Montréal",
        province: "QC",
        postalcode: "H1T1S6",
        country: "Canada",
        lat: 45.56413,
        lng: -73.57812,
        proximity: {
          linear_distance: 3513,
        },
      },
      {
        name: "Metro",
        address: "3800 Rue Ontario E",
        city: "Montréal",
        province: "QC",
        postalcode: "H1W1S4",
        country: "Canada",
        lat: 45.54736,
        lng: -73.5432,
        url: "http://metro.ca",
        proximity: {
          linear_distance: 3669,
        },
      },
      {
        name: "Alfred Groceries",
        address: "405 Saint-Claude Rue",
        city: "Montréal",
        province: "QC",
        postalcode: "H2Y3B6",
        country: "Canada",
        lat: 45.50879,
        lng: -73.55211,
        proximity: {
          linear_distance: 3746,
        },
      },
      {
        name: "SRC Alimentation",
        address: "507 Place D'armes",
        city: "Montréal",
        province: "QC",
        postalcode: "H2Y2W8",
        country: "Canada",
        lat: 45.504989,
        lng: -73.55676,
        url: "http://lesalimentssrc.ca",
        proximity: {
          linear_distance: 3837,
        },
      },
      {
        name: "Super C",
        address: "2050 Boulevard Pie-IX",
        city: "Montréal",
        province: "QC",
        postalcode: "H1V2C8",
        country: "Canada",
        lat: 45.55067,
        lng: -73.54276,
        url: "http://superc.ca",
        proximity: {
          linear_distance: 3873,
        },
      },
      {
        name: "Marcha Malo",
        address: "4737 Hochelaga Rue",
        city: "Montréal",
        province: "QC",
        postalcode: "H1V1E2",
        country: "Canada",
        lat: 45.55931,
        lng: -73.54419,
        proximity: {
          linear_distance: 4356,
        },
      },
    ],
  },
  meta: {
    message: "Successfully called v3/pois API.",
    type: "LocalLogic.API.Success",
    statusCode: 200,
    counts: {
      groceries: 82,
    },
  },
};
